import os
import re
import shutil
import zipfile

import joblib


def _safe_python_name(name):
    """
    Convert a dataframe column name into a valid Python identifier.
    """

    name = str(name)

    name = re.sub(
        r"\W+",
        "_",
        name
    )

    name = name.strip("_")

    if not name:
        name = "feature"

    if name[0].isdigit():
        name = f"feature_{name}"

    return name


def export_fastapi_project(model, feature_names):
    """
    Create a ready-to-run FastAPI deployment package.

    Package contains:

        app.py
        model.pkl
        requirements.txt
        README.md
        sample_request.json
        Dockerfile
        docker-compose.yml
    """

    folder = "deployment"

    # ==========================================
    # Remove previous deployment
    # ==========================================

    if os.path.exists(folder):

        shutil.rmtree(folder)

    os.makedirs(
        folder,
        exist_ok=True
    )

    # ==========================================
    # Save trained model
    # ==========================================

    model_path = os.path.join(
        folder,
        "model.pkl"
    )

    joblib.dump(
        model,
        model_path
    )

    # ==========================================
    # Prepare feature names
    # ==========================================

    feature_mapping = []

    used_names = set()

    for feature in feature_names:

        original_name = str(feature)

        safe_name = _safe_python_name(
            original_name
        )

        # Prevent duplicate Python names
        base_name = safe_name
        counter = 2

        while safe_name in used_names:

            safe_name = (
                f"{base_name}_{counter}"
            )

            counter += 1

        used_names.add(safe_name)

        feature_mapping.append(
            (
                original_name,
                safe_name
            )
        )

    # ==========================================
    # Generate Pydantic request fields
    # ==========================================

    request_fields = []

    for _, safe_name in feature_mapping:

        request_fields.append(
            f"    {safe_name}: object"
        )

    feature_fields = "\n".join(
        request_fields
    )

    # ==========================================
    # Generate FastAPI application
    # ==========================================

    app_code = '''from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd


app = FastAPI(
    title="DataVerse Model API",
    description="Machine Learning prediction API generated by DataVerse.",
    version="1.0.0"
)


# ==========================================
# Load Model
# ==========================================

model = joblib.load("model.pkl")


# ==========================================
# Request Schema
# ==========================================

class PredictionRequest(BaseModel):

'''

    app_code += feature_fields

    app_code += '''


# ==========================================
# Home Endpoint
# ==========================================

@app.get("/")
def home():

    return {
        "message": "DataVerse Model API is running.",
        "status": "online"
    }


# ==========================================
# Prediction Endpoint
# ==========================================

@app.post("/predict")
def predict(data: PredictionRequest):

    input_data = {
'''

    for original_name, safe_name in feature_mapping:

        app_code += (
            f'        "{original_name}": '
            f'data.{safe_name},\n'
        )

    app_code += '''    }

    dataframe = pd.DataFrame([input_data])

    prediction = model.predict(dataframe)

    return {
        "prediction": prediction.tolist()
    }
}
'''

    # ==========================================
    # Save app.py
    # ==========================================

    with open(
        os.path.join(
            folder,
            "app.py"
        ),
        "w",
        encoding="utf-8"
    ) as file:

        file.write(app_code)

    # ==========================================
    # requirements.txt
    # ==========================================

    requirements = """fastapi
uvicorn
pydantic
pandas
numpy
scikit-learn
joblib
"""

    with open(
        os.path.join(
            folder,
            "requirements.txt"
        ),
        "w",
        encoding="utf-8"
    ) as file:

        file.write(requirements)

    # ==========================================
    # README.md
    # ==========================================

    readme = """# DataVerse Model API

This API was automatically generated by DataVerse.

## Installation

Install the required dependencies:

```bash
pip install -r requirements.txt"""