from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


def generate_report(df, metrics):

    filename = "DataVerse_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph(
            "<b>DataVerse AI Report</b>",
            styles["Title"]
        )
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "<b>Dataset Summary</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            f"Rows : {df.shape[0]}",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"Columns : {df.shape[1]}",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"Missing Values : {int(df.isnull().sum().sum())}",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"Duplicate Rows : {int(df.duplicated().sum())}",
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "<b>Model Performance</b>",
            styles["Heading2"]
        )
    )

    for metric, value in metrics.items():

        elements.append(
            Paragraph(
                f"{metric} : {value:.4f}",
                styles["BodyText"]
            )
        )

    elements.append(Spacer(1, 30))

    elements.append(
        Paragraph(
            "Generated by DataVerse AI",
            styles["Italic"]
        )
    )

    doc.build(elements)

    return filename